name: Fork AdRules

on:
  workflow_dispatch:
  schedule:
    - cron: "55 23,11 * * *"
  
jobs:
  ForkAdRules:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.7
    
    - name: Create directories
      run: mkdir -p temp Rule

    - name: Clone files
      run: |
        curl -sSL -o temp/adrules.list https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules.list
        curl -sSL -o temp/anti-ad-surge.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt

    - name: Process files
      run: |
        process_file() {
          local input1=$1
          local input2=$2
          local output=$3
          local transformations=$4
          local rule_name=$5

          creation_date=$(TZ='Asia/Shanghai' date +"%Y-%m-%d %H:%M:%S")
          cat "$input1" "$input2" | sort -u > temp/mfile.tmp
          sed -i -e '/^\s*[#;]/d' -e '/^$/d' temp/mfile.tmp
          eval "$transformations"
          rule_count=$(wc -l < temp/mfile.tmp | tr -d ' ')
          echo "# 规则名称: $rule_name" > "$output"
          echo "# 规则数量: $rule_count" >> "$output"
          echo "# 更新时间: $creation_date" >> "$output"
          cat temp/mfile.tmp >> "$output"
          rm temp/mfile.tmp
          sed -i '3a\\' "$output"
        }

        process_file "temp/adrules.list" "temp/anti-ad-surge.txt" "Rule/AdBlock.list" "" "AdBlock"
        process_file "temp/adrules.list" "temp/anti-ad-surge.txt" "Rule/AdBlockQX.list" "sed -i -e 's/DOMAIN-SUFFIX,/HOST-SUFFIX,/g' temp/mfile.tmp" "AdBlock"
        process_file "temp/adrules.list" "temp/anti-ad-surge.txt" "Rule/AdBlock.yaml" "sed -i -e 's/DOMAIN-SUFFIX,/- /g' temp/mfile.tmp && sed -i '1i\no_resolve: true' temp/mfile.tmp && sed -i '2i\domain_set:' temp/mfile.tmp && sed -i '3i\domain_suffix_set:' temp/mfile.tmp" "AdBlock"
        process_file "temp/adrules.list" "temp/anti-ad-surge.txt" "Rule/Antiad.yaml" "sed -i -e 's/DOMAIN-SUFFIX,/  - DOMAIN,/g' temp/mfile.tmp && sed -i '1i\payload:' temp/mfile.tmp" "Antiad"
        process_file "temp/adrules.list" "temp/anti-ad-surge.txt" "Rule/Antiad.list" "sed -i -e 's/DOMAIN-SUFFIX,/DOMAIN,/g' temp/mfile.tmp" "Antiad"

    - name: Cleanup temp directory
      run: rm -rf temp

    - name: Add and Commits
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git pull --rebase origin X
          git push origin X  
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
