name: Fork QuantumultX

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22,10 * * *"
  
jobs:
  Fork-QuantumultX:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.5
    
      # 拉取文件
    - name: Clone
      run: |
        rm -rf Rules/QuantumultX/Rule/*
        mkdir -p Rules/QuantumultX/Rule
        git clone https://github.com/blackmatrix7/ios_rule_script.git temp_directory
        cp -r temp_directory/rule/QuantumultX/* QuantumultX/Rule/
        rm -rf temp_directory    
 

    - name: Edit files
      run: |
        cd QuantumultX/Rule
        # Edit '.list' files
        find . -type f -name '*.list' -print0 | while IFS= read -r -d $'\0' file; do
          if [ -f "$file" ]; then
            sed -i '2,3d' "$file"
          fi
        done

    - name: Edit README
      run: |
        cd QuantumultX/Rule
        find . -type f -name 'README.md' -print0 | while IFS= read -r -d $'\0' readme; do
          if [ -f "$readme" ]; then
            # 删除和替换指定的字符串
            sed -i -e '/\*\*MASTER分支 CDN (每日更新)\*\*/d' \
                   -e '/\*\*MASTER分支 GHProxy (每日更新)\*\*/d' \
                   -e '/\(不定时更新\)/d' \
                   -e '/blackmatrix7\/ios_rule_script\/release\/rule\/QuantumultX/d' \
                   -e '/https:\/\/cdn.jsdelivr.net/d' \
                   -e '/https:\/\/ghproxy.com/d' \
                   -e 's|MASTER分支|分支|g' \
                   -e 's|## QuantumultX|## QuantumultX|g' \
                   -e 's|blackmatrix7/ios_rule_script/master/rule/QuantumultX|Asimplersir/Rules/X/QuantumultX/Rule|g' \
                   -e 's|github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX|github.com/Asimplersir/Rules/tree/X/QuantumultX/Rule|g' \
                   -e 's|USER-AGENT|USER-AGENT(QuantumultX支持)|g' \
                   -e 's|TOTAL|TOTAL(仅供参考)|g' \
                   -e 's|QuantumultX定制化规则|QuantumultX定制化规则|g' \
                   -e 's|Asimplersir/Rules/X/QuantumultX/Rule/\(.*\)\.list|Asimplersir/Rules/X/QuantumultX/Rule/\1.list|g' \
                   -e 's|-\([[:space:]]*\)\([A-Za-z0-9_]*\)\.list|-\1\2.list|' \
                   "$readme"
          else
            echo "$readme not found."
          fi
        done

    - name: Add and Commits
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push 
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

