name: Fork Stash

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22,10 * * *"
  
jobs:
  Fork-Stash:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.5
    
      # 拉取文件
    - name: Clone
      run: |
        rm -rf Rules/Stash/Rule/*
        mkdir -p Rules/Stash/Rule
        git clone https://github.com/blackmatrix7/ios_rule_script.git temp_directory
        cp -r temp_directory/rule/Clash/* Stash/Rule/
        rm -rf temp_directory    
 
      # 编辑文件
    - name: Edit files
      run: |
        cd Stash/Rule
        # Edit '.list' files
        find . -type f -name '*.list' -print0 | while IFS= read -r -d $'\0' file; do
          if [ -f "$file" ]; then
            sed -i '2,3d' "$file"
          fi
        done

        # Edit '.yaml' files
        find . -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file; do
          if [ -f "$file" ]; then
            sed -i '2,3d' "$file"
          fi
        done

        # Edit '.txt' files
        find . -type f -name '*.txt' -print0 | while IFS= read -r -d $'\0' file; do
          if [ -f "$file" ]; then
            sed -i '2,3d' "$file"
          fi
        done

    - name: Edit README
      run: |
        cd Stash/Rule
        find . -type f -name 'README.md' -print0 | while IFS= read -r -d $'\0' readme; do
          if [ -f "$readme" ]; then
            # 删除和替换指定的字符串
            sed -i -e '/\*\*MASTER分支 CDN (每日更新)\*\*/d' \
                   -e '/\*\*MASTER分支 GHProxy (每日更新)\*\*/d' \
                   -e '/\(不定时更新\)/d' \
                   -e '/blackmatrix7\/ios_rule_script\/release\/rule\/Clash/d' \
                   -e '/https:\/\/cdn.jsdelivr.net/d' \
                   -e '/https:\/\/ghproxy.com/d' \
                   -e 's|MASTER分支|分支|g' \
                   -e 's|## Clash|## Stash|g' \
                   -e 's|blackmatrix7/ios_rule_script/master/rule/Clash|Asimplersir/Rules/X/Stash/Rule/|g' \
                   -e 's|github.com/blackmatrix7/ios_rule_script/tree/master/rule/Clash|github.com/Asimplersir/Rules/tree/X/Stash/Rule/|g' \
                   -e 's|USER-AGENT|USER-AGENT(Stash支持)|g' \
                   -e 's|TOTAL|TOTAL(仅供参考)|g' \
                   -e 's|Clash定制化规则|Stash定制化规则|g' \
                   -e 's|Asimplersir/Rules/X/Stash/Rule/\(.*\)\.yaml|Asimplersir/Rules/X/Stash/Rule/\1.yaml|g' \
                   -e 's|-\([[:space:]]*\)\([A-Za-z0-9_]*\)\.yaml|-\1\2.yaml|' \
                   "$readme"
          else
            echo "$readme not found."
          fi
        done

    - name: Add and Commits
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push 
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

